name: CI/CD Deploy Frontend

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 
          
      - name: "Create .env file"
        run: |
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> .env
          echo "VITE_S3_BASE_URL=${{ secrets.VITE_S3_BASE_URL }}" >> .env


      - name: "Get Runner IP"
        id: get_ip
        run: |
            echo "RUNNER_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV
            echo $RUNNER_IP

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
            
      - name: "Add runner ip in aws security group"
        run: |
            aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.RUNNER_IP }}/32
          
      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to EC2
        run: |         
           echo "${{ secrets.EC2_KEY }}" > private_key.pem
           chmod 600 private_key.pem
           ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p /var/www/html/vip-studio-schedule/dist"          
          
           rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --delete $GITHUB_WORKSPACE/dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/vip-studio-schedule/dist/    
          
           ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
           sudo chown -R ubuntu:www-data /var/www/html/vip-studio-schedule/dist &&
           sudo chmod -R 755 /var/www/html/vip-studio-schedule/dist &&
           sudo systemctl reload nginx"

      - name: "Remove runner ip from aws security group"
        run: |
            aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.RUNNER_IP }}/32
